"""Self-contained HTML report generator for ACHA"""

import html
from datetime import datetime
from pathlib import Path
from typing import Any


class HTMLReporter:
    """Generate self-contained HTML reports with inline CSS and JavaScript"""

    def __init__(self):
        """Initialize HTML reporter"""
        pass

    def generate(
        self,
        analysis: dict | None = None,
        patch: dict | None = None,
        validation: dict | None = None,
        target_path: str = ".",
    ) -> str:
        """
        Generate self-contained HTML report.

        Args:
            analysis: Analysis results dictionary
            patch: Patch summary dictionary
            validation: Validation results dictionary
            target_path: Path to analyzed project

        Returns:
            Complete HTML document as string
        """
        analysis = analysis or {}
        patch = patch or {}
        validation = validation or {}

        findings = analysis.get("findings", [])

        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ACHA Code Health Report</title>
    <style>
{self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🏥 ACHA Code Health Report</h1>
            <p class="subtitle">Automated Code Health Agent - Analysis Report</p>
            <p class="timestamp">Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <p class="target-path">Target: <code>{html.escape(target_path)}</code></p>
        </header>

        {self._build_summary_cards(analysis, patch, validation)}

        {self._build_findings_section(findings)}

        {self._build_patch_section(patch)}

        {self._build_validation_section(validation)}

        <footer>
            <p>Generated by ACHA v0.3.0 | <a href="https://github.com/woozyrabbit123/acha-code-health-agent">GitHub</a></p>
        </footer>
    </div>

    <script>
{self._get_javascript()}
    </script>
</body>
</html>"""

        return html_content

    def _get_css(self) -> str:
        """Get inline CSS styles"""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        :root {
            --bg-primary: #ffffff;
            --bg-secondary: #f5f5f5;
            --bg-card: #ffffff;
            --text-primary: #333333;
            --text-secondary: #666666;
            --border-color: #e0e0e0;
            --accent-color: #4CAF50;
            --error-color: #f44336;
            --warning-color: #ff9800;
            --info-color: #2196F3;
            --shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        @media (prefers-color-scheme: dark) {
            :root {
                --bg-primary: #1e1e1e;
                --bg-secondary: #2d2d2d;
                --bg-card: #252525;
                --text-primary: #e0e0e0;
                --text-secondary: #b0b0b0;
                --border-color: #404040;
                --shadow: 0 2px 4px rgba(0,0,0,0.3);
            }
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: var(--text-primary);
            background: var(--bg-primary);
            padding: 20px;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
        }

        header {
            text-align: center;
            margin-bottom: 40px;
            padding: 30px 20px;
            background: var(--bg-card);
            border-radius: 8px;
            box-shadow: var(--shadow);
        }

        h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
            color: var(--accent-color);
        }

        .subtitle {
            font-size: 1.2em;
            color: var(--text-secondary);
            margin-bottom: 10px;
        }

        .timestamp, .target-path {
            font-size: 0.9em;
            color: var(--text-secondary);
        }

        code {
            background: var(--bg-secondary);
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
            font-size: 0.9em;
        }

        .summary-cards {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-bottom: 40px;
        }

        .card {
            background: var(--bg-card);
            padding: 20px;
            border-radius: 8px;
            box-shadow: var(--shadow);
            border-left: 4px solid var(--accent-color);
        }

        .card.error {
            border-left-color: var(--error-color);
        }

        .card.warning {
            border-left-color: var(--warning-color);
        }

        .card.info {
            border-left-color: var(--info-color);
        }

        .card-title {
            font-size: 0.9em;
            color: var(--text-secondary);
            text-transform: uppercase;
            margin-bottom: 10px;
        }

        .card-value {
            font-size: 2.5em;
            font-weight: bold;
            color: var(--text-primary);
        }

        .section {
            background: var(--bg-card);
            padding: 30px;
            border-radius: 8px;
            box-shadow: var(--shadow);
            margin-bottom: 30px;
        }

        .section-title {
            font-size: 1.8em;
            margin-bottom: 20px;
            color: var(--text-primary);
            border-bottom: 2px solid var(--border-color);
            padding-bottom: 10px;
        }

        .controls {
            margin-bottom: 20px;
            display: flex;
            gap: 15px;
            flex-wrap: wrap;
        }

        .control-group {
            display: flex;
            align-items: center;
            gap: 8px;
        }

        label {
            font-size: 0.9em;
            color: var(--text-secondary);
        }

        input[type="text"], select {
            padding: 8px 12px;
            border: 1px solid var(--border-color);
            border-radius: 4px;
            background: var(--bg-secondary);
            color: var(--text-primary);
            font-size: 0.9em;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }

        th {
            background: var(--bg-secondary);
            padding: 12px;
            text-align: left;
            font-weight: 600;
            border-bottom: 2px solid var(--border-color);
            cursor: pointer;
            user-select: none;
        }

        th:hover {
            background: var(--border-color);
        }

        td {
            padding: 12px;
            border-bottom: 1px solid var(--border-color);
        }

        tr:hover {
            background: var(--bg-secondary);
        }

        .severity-badge {
            display: inline-block;
            padding: 4px 10px;
            border-radius: 12px;
            font-size: 0.85em;
            font-weight: 600;
            text-transform: uppercase;
        }

        .severity-critical {
            background: #f44336;
            color: white;
        }

        .severity-error {
            background: #ff5722;
            color: white;
        }

        .severity-warning {
            background: #ff9800;
            color: white;
        }

        .severity-info {
            background: #2196F3;
            color: white;
        }

        .no-findings {
            text-align: center;
            padding: 40px;
            color: var(--text-secondary);
            font-size: 1.1em;
        }

        .diff-viewer {
            background: var(--bg-secondary);
            border: 1px solid var(--border-color);
            border-radius: 4px;
            padding: 15px;
            overflow-x: auto;
            font-family: 'Courier New', monospace;
            font-size: 0.85em;
            line-height: 1.4;
            max-height: 500px;
            overflow-y: auto;
        }

        .diff-line {
            padding: 2px 0;
        }

        .diff-add {
            background: #e6ffed;
            color: #22863a;
        }

        .diff-remove {
            background: #ffeef0;
            color: #b31d28;
        }

        @media (prefers-color-scheme: dark) {
            .diff-add {
                background: #1a3a25;
                color: #85e89d;
            }

            .diff-remove {
                background: #3a1a1a;
                color: #f97583;
            }
        }

        .test-result {
            padding: 15px;
            border-radius: 4px;
            margin: 10px 0;
        }

        .test-pass {
            background: #e8f5e9;
            border-left: 4px solid #4CAF50;
        }

        .test-fail {
            background: #ffebee;
            border-left: 4px solid #f44336;
        }

        @media (prefers-color-scheme: dark) {
            .test-pass {
                background: #1b5e20;
            }

            .test-fail {
                background: #b71c1c;
            }
        }

        footer {
            text-align: center;
            padding: 30px;
            color: var(--text-secondary);
            font-size: 0.9em;
        }

        footer a {
            color: var(--accent-color);
            text-decoration: none;
        }

        footer a:hover {
            text-decoration: underline;
        }

        @media (max-width: 768px) {
            body {
                padding: 10px;
            }

            h1 {
                font-size: 1.8em;
            }

            .summary-cards {
                grid-template-columns: 1fr;
            }

            .section {
                padding: 20px 15px;
            }

            table {
                font-size: 0.9em;
            }

            th, td {
                padding: 8px;
            }
        }
"""

    def _get_javascript(self) -> str:
        """Get inline JavaScript"""
        return """
        // Table sorting
        document.querySelectorAll('th[data-sort]').forEach(header => {
            header.addEventListener('click', function() {
                const table = this.closest('table');
                const tbody = table.querySelector('tbody');
                const rows = Array.from(tbody.querySelectorAll('tr'));
                const column = this.dataset.sort;
                const currentOrder = this.dataset.order || 'asc';
                const newOrder = currentOrder === 'asc' ? 'desc' : 'asc';

                rows.sort((a, b) => {
                    const aValue = a.querySelector(`[data-${column}]`)?.dataset[column] || '';
                    const bValue = b.querySelector(`[data-${column}]`)?.dataset[column] || '';

                    const comparison = aValue.localeCompare(bValue, undefined, { numeric: true });
                    return newOrder === 'asc' ? comparison : -comparison;
                });

                // Clear order indicators
                table.querySelectorAll('th').forEach(th => delete th.dataset.order);
                this.dataset.order = newOrder;

                // Re-append rows
                rows.forEach(row => tbody.appendChild(row));
            });
        });

        // Filter functionality
        const filterInput = document.getElementById('findingFilter');
        const severityFilter = document.getElementById('severityFilter');

        function filterFindings() {
            const searchText = filterInput?.value.toLowerCase() || '';
            const severity = severityFilter?.value || 'all';

            document.querySelectorAll('.findings-table tbody tr').forEach(row => {
                const text = row.textContent.toLowerCase();
                const rowSeverity = row.querySelector('[data-severity]')?.dataset.severity || '';

                const textMatch = text.includes(searchText);
                const severityMatch = severity === 'all' || rowSeverity.includes(severity);

                row.style.display = (textMatch && severityMatch) ? '' : 'none';
            });
        }

        if (filterInput) {
            filterInput.addEventListener('input', filterFindings);
        }

        if (severityFilter) {
            severityFilter.addEventListener('change', filterFindings);
        }
"""

    def _build_summary_cards(self, analysis: dict, patch: dict, validation: dict) -> str:
        """Build summary cards section"""
        findings = analysis.get("findings", [])
        total_findings = len(findings)

        # Count by severity
        severity_counts = {"critical": 0, "error": 0, "warning": 0, "info": 0}
        for finding in findings:
            sev = finding.get("severity", 0.1)
            if isinstance(sev, (int, float)):
                if sev >= 0.9:
                    severity_counts["critical"] += 1
                elif sev >= 0.7:
                    severity_counts["error"] += 1
                elif sev >= 0.4:
                    severity_counts["warning"] += 1
                else:
                    severity_counts["info"] += 1
            else:
                sev_str = str(sev).lower()
                if sev_str in severity_counts:
                    severity_counts[sev_str] += 1

        files_touched = len(patch.get("files_touched", []))
        test_status = validation.get("status", "unknown")

        return f"""
        <div class="summary-cards">
            <div class="card">
                <div class="card-title">Total Findings</div>
                <div class="card-value">{total_findings}</div>
            </div>
            <div class="card error">
                <div class="card-title">Critical/Errors</div>
                <div class="card-value">{severity_counts['critical'] + severity_counts['error']}</div>
            </div>
            <div class="card warning">
                <div class="card-title">Warnings</div>
                <div class="card-value">{severity_counts['warning']}</div>
            </div>
            <div class="card info">
                <div class="card-title">Info</div>
                <div class="card-value">{severity_counts['info']}</div>
            </div>
            <div class="card">
                <div class="card-title">Files Touched</div>
                <div class="card-value">{files_touched}</div>
            </div>
            <div class="card {'error' if test_status == 'fail' else 'info'}">
                <div class="card-title">Tests</div>
                <div class="card-value">{test_status.upper() if test_status != 'unknown' else 'N/A'}</div>
            </div>
        </div>
"""

    def _build_findings_section(self, findings: list[dict]) -> str:
        """Build findings table section"""
        if not findings:
            return """
        <div class="section">
            <h2 class="section-title">📊 Findings</h2>
            <div class="no-findings">✅ No findings detected. Great job!</div>
        </div>
"""

        # Build table rows
        rows = []
        for i, finding in enumerate(findings):
            severity = finding.get("severity", 0.1)
            severity_str = self._format_severity(severity)
            severity_class = self._get_severity_class(severity)

            file_name = html.escape(finding.get("file", "unknown"))
            line = finding.get("line") or finding.get("start_line", "?")
            rule = html.escape(finding.get("finding") or finding.get("rule", "unknown"))
            rationale = html.escape(finding.get("rationale") or finding.get("message", ""))

            rows.append(
                f"""
                <tr>
                    <td data-severity="{severity_str}">{i+1}</td>
                    <td data-severity="{severity_str}">
                        <span class="severity-badge severity-{severity_class}">{severity_str}</span>
                    </td>
                    <td data-file="{file_name}"><code>{file_name}</code></td>
                    <td data-line="{line}">{line}</td>
                    <td data-rule="{rule}">{rule}</td>
                    <td>{rationale}</td>
                </tr>
            """
            )

        return f"""
        <div class="section">
            <h2 class="section-title">📊 Findings</h2>

            <div class="controls">
                <div class="control-group">
                    <label for="findingFilter">Filter:</label>
                    <input type="text" id="findingFilter" placeholder="Search findings...">
                </div>
                <div class="control-group">
                    <label for="severityFilter">Severity:</label>
                    <select id="severityFilter">
                        <option value="all">All</option>
                        <option value="critical">Critical</option>
                        <option value="error">Error</option>
                        <option value="warning">Warning</option>
                        <option value="info">Info</option>
                    </select>
                </div>
            </div>

            <table class="findings-table">
                <thead>
                    <tr>
                        <th data-sort="number">#</th>
                        <th data-sort="severity">Severity</th>
                        <th data-sort="file">File</th>
                        <th data-sort="line">Line</th>
                        <th data-sort="rule">Rule</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    {''.join(rows)}
                </tbody>
            </table>
        </div>
"""

    def _build_patch_section(self, patch: dict) -> str:
        """Build patch/refactoring section"""
        if not patch or not patch.get("files_touched"):
            return ""

        files = patch.get("files_touched", [])
        lines_added = patch.get("lines_added", 0)
        lines_removed = patch.get("lines_removed", 0)
        notes = patch.get("notes", [])

        notes_html = "".join([f"<li>{html.escape(note)}</li>" for note in notes])

        return f"""
        <div class="section">
            <h2 class="section-title">🔧 Refactoring Applied</h2>
            <p><strong>Patch ID:</strong> <code>{html.escape(patch.get('patch_id', 'N/A'))}</code></p>
            <p><strong>Files Modified:</strong> {len(files)}</p>
            <p><strong>Lines Changed:</strong> +{lines_added} / -{lines_removed}</p>

            {f'<h3>Changes:</h3><ul>{notes_html}</ul>' if notes else ''}

            <details>
                <summary style="cursor: pointer; font-weight: bold; margin: 15px 0;">Modified Files</summary>
                <ul>
                    {''.join([f'<li><code>{html.escape(f)}</code></li>' for f in files])}
                </ul>
            </details>
        </div>
"""

    def _build_validation_section(self, validation: dict) -> str:
        """Build validation/test results section"""
        if not validation or validation.get("status") == "unknown":
            return ""

        status = validation.get("status", "unknown")
        output = validation.get("output", "")
        tests_run = validation.get("tests_run", 0)
        tests_passed = validation.get("tests_passed", 0)

        status_class = "test-pass" if status == "pass" else "test-fail"
        status_emoji = "✅" if status == "pass" else "❌"

        return f"""
        <div class="section">
            <h2 class="section-title">🧪 Validation Results</h2>

            <div class="{status_class}" style="margin: 15px 0;">
                <strong>{status_emoji} Status:</strong> {status.upper()}
                {f'<br><strong>Tests:</strong> {tests_passed}/{tests_run} passed' if tests_run > 0 else ''}
            </div>

            {f'<details><summary style="cursor: pointer; font-weight: bold; margin: 15px 0;">Test Output</summary><pre class="diff-viewer">{html.escape(output)}</pre></details>' if output else ''}
        </div>
"""

    def _format_severity(self, severity: Any) -> str:
        """Format severity for display"""
        if isinstance(severity, str):
            return severity.lower()

        if isinstance(severity, (int, float)):
            if severity >= 0.9:
                return "critical"
            elif severity >= 0.7:
                return "error"
            elif severity >= 0.4:
                return "warning"
            else:
                return "info"

        return "info"

    def _get_severity_class(self, severity: Any) -> str:
        """Get CSS class for severity"""
        return self._format_severity(severity)

    def write(self, html_content: str, output_path: Path):
        """Write HTML to file"""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html_content)

    def generate_and_write(
        self,
        output_path: Path,
        analysis: dict | None = None,
        patch: dict | None = None,
        validation: dict | None = None,
        target_path: str = ".",
    ):
        """Generate and write HTML report"""
        html_content = self.generate(analysis, patch, validation, target_path)
        self.write(html_content, output_path)
